<?php

function curd_menu(){
	$items = array();
	$items['curd/new']=array(
	'title' => 'CURD From',
	'description' => 'This module provide CURD Orations',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('curd_form'),
	'access callback'=>TRUE 
	);
	return $items;
}

function curd_form($form, &$form_state){
	
	$form['name'] = array(
		'#title' => 'username',
		'#description' => 'choose a username',
		'#type' => 'textfield',
		'#required' => TRUE,
	);
	$form['mail'] = array(
		'#title' => 'email',
		'#description' => 'enter a valid email address',
		'#type' => 'textfield',
		'#required' => TRUE,
	);
        $form['field_fname'] = array(
		'#title' => 'First Name',
		'#type' => 'textfield',
	);
        $form['field_lname'] = array(
		'#title' => 'Last Name',
		'#type' => 'textfield',
	);
        $form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);
  
  return $form;
}

function curd_form_validate($form, &$form_state) {
	/*if (!($form_state['values']['price'] > 0)){
		form_set_error('price', t('Price must be a positive number.'));
	} */
	
	
	
}

function curd_form_submit($form, &$form_state) {
	
	$edit = array(
	      'name' => $form_state['values']['name'], 
	      'pass' => user_password(),
	      'mail' => $form_state['values']['mail'],
	      'init' => $form_state['values']['mail'], 
	      'status' => 1, 
	      'access' => REQUEST_TIME,
          'field_fname' => array(LANGUAGE_NONE => array(array('value' => $form_state['values']['field_fname']))),
	      'field_lname' => array(LANGUAGE_NONE => array(array('value' => $form_state['values']['field_lname']))),
	);
	user_save(drupal_anonymous_user(), $edit);
	drupal_set_message('Data successfully saved!');
}